version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    groups:
      tree-sitter:
        patterns:
          - "tree-sitter*"
  - package-ecosystem: cargo
    directory: "/enums"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    ignore:
      - dependency-name: "tree-sitter*"
