[package]
name = "mehen"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["metrics"]
description = "Tool to compute and export code metrics"
license.workspace = true

[dependencies]
clap = { version = "^4.5", features = ["derive"] }
crossbeam = { version = "^0.8", features = ["crossbeam-channel"] }
env_logger = "^0.11"
globset = "^0.4"
log = "^0.4"
num = "^0.4"
num-derive = "^0.4"
num-format = "^0.4"
num-traits = "^0.2"
owo-colors = "^4"
regex = "^1.7"
serde = { version = "^1.0", features = ["derive"] }
serde_cbor = "^0.11"
serde_json = "^1.0"
serde_norway = "^0.9"
toml = "^1.0"
walkdir = "^2.3"
gix = { version = "^0.79", default-features = false, features = ["max-performance-safe", "revision"] }

tree-sitter = "=0.26.5"
tree-sitter-typescript = "=0.23.2"
tree-sitter-python = "=0.25.0"
tree-sitter-rust = "=0.24.0"
tree-sitter-go = "=0.25.0"

[package.metadata.cargo-machete]
ignored = ["num-traits", "tree-sitter-go", "tree-sitter-python", "tree-sitter-rust"]

[dev-dependencies]
insta = { version = "1.29.0", features = ["yaml", "json", "redactions"] }
pretty_assertions = "^1.3"

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3

[workspace]
exclude = ["enums"]

[workspace.package]
version = "0.0.4"
authors = ["Konstantin Vyatkin <tino@vtkn.io>"]
edition = "2024"
rust-version = "1.93.1"
repository = "https://github.com/ophidiarium/mehen"
license = "MPL-2.0"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "unwind"
incremental = false
overflow-checks = false
strip = "debuginfo"
