[profile.ci]
# Print out output for failing tests as soon as they fail, and also at the end
# of the run (for easy scrollability).
failure-output = "immediate-final"
# Do not cancel the test run on the first failure.
fail-fast = false
# Snapshot assertions (insta) should not be retried since reruns add noise and
# can produce confusing pending-snapshot states.
retries = 0

status-level = "skip"

# Mark tests that take longer than 2s as slow.
# Terminate after 5min as a stop-gap measure to terminate on deadlock.
slow-timeout = { period = "2s", terminate-after = 300 }

# Show slow jobs in the final summary
final-status-level = "slow"

[profile.ci.junit]
path = "junit.xml"
